version: "3"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: ./Dockerfile
    container_name: rental_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./data/rabbitmq_data:/var/lib/rabbitmq/mnesia"
    networks:
      - app-net

  customer-db:
    container_name: customer-db
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - "./data/customer_db:/var/lib/postgresql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=customer_db
    networks:
      - app-net

  customer-service:
    container_name: customer-service
    build:
      context: ./ms-customer
      dockerfile: ./Dockerfile
    depends_on:
      - rabbitmq
      - customer-db
    volumes:
      - ./:/usr/src/app
    ports:
      - 5001:5001

  rental-db:
    container_name: rental-db
    image: "postgres:alpine"
    ports:
      - "15432:5432"
    volumes:
      - "./data/rental_db:/var/lib/postgresql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rental_db
    networks:
      - app-net

  rental-service:
    container_name: rental-service
    build:
      context: ./ms-rental
      dockerfile: ./Dockerfile
    depends_on:
      - rabbitmq
      - rental-db
    volumes:
      - ./:/usr/src/app
    ports:
      - 5002:5002

networks:
  app-net:
    driver: bridge
