version: '3'

services:
  admin-db:
    container_name: admin-db
    image: 'postgres:alpine'
    ports:
      - '25432:5432'
    volumes:
      - './data:/var/lib/postgresql'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    networks:
      - app-net

  admin-service:
    container_name: admin-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5003:5003

networks:
  app-net:
    driver: bridge
