import axios from "axios";
import jwt from "jsonwebtoken";
import type { NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import { parseCookies } from "nookies";
import { useContext, useEffect, useState } from "react";
// import { AuthContext } from "../context/AuthContext";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  // const { isAuthenticated, customer, setCustomer } = useContext(AuthContext);

  // useEffect(() => {
  //   if (isAuthenticated) {
  //     Router.push("/orders");
  //   } else {
  //     Router.push("/signin");
  //   }
  // }, []);

  useEffect(() => {
    Router.push("/orders");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
